In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import math
from sklearn import metrics
import pickle

In [2]:
data=pd.read_csv('Dimuon_DoubleMu.csv')

In [3]:
data=data.sample(frac=1)
data.drop(['Run','Event','type1'],axis=1,inplace=True)
#data= data.set_index('Event')
data

,E1,px1,py1,pz1,pt1,eta1,phi1,Q1,type2,E2,px2,py2,pz2,pt2,eta2,phi2,Q2,M
85820,22.5163,-6.9052,0.0043,-21.4311,6.9052,-1.8507,3.1410,1,G,12.3470,9.8277,-1.1906,-7.3781,9.8995,-0.6894,-0.1206,-1,19.3787
38382,21.4797,-1.3635,8.2428,19.7880,8.3549,1.5972,1.7347,1,G,9.6164,-0.3583,-9.5918,0.5767,9.5985,0.0601,-1.6081,-1,23.3979
15831,8.8509,2.3816,-3.7905,-7.6346,4.4766,-1.3036,-1.0098,1,G,15.8228,-1.9776,3.8813,15.2110,4.3561,1.9635,2.0420,-1,23.4780
82644,8.3517,-0.9383,-5.0395,6.5927,5.1261,1.0700,-1.7549,-1,G,6.7072,2.6261,5.9184,-1.7471,6.4748,-0.2667,1.1532,1,14.1305
7802,6.0043,2.9144,-4.7209,2.2933,5.5481,0.4024,-1.0177,-1,G,6.5077,-2.6093,5.1598,-2.9846,5.7820,-0.4956,2.0390,1,12.4814
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48193,9.8275,-8.4420,-4.2769,2.6473,9.4636,0.2762,-2.6727,1,G,6.5832,-4.4583,-4.7770,0.7942,6.5343,0.1212,-2.3217,-1,3.0122
64597,19.0896,16.2683,-8.2099,5.6869,18.2225,0.3072,-0.4674,1,G,7.6293,5.4447,-3.7040,3.8510,6.5852,0.5557,-0.5974,-1,3.0871
38959,6.8210,-0.0452,-6.6651,1.4452,6.6653,0.2152,-1.5776,1,G,6.0991,-2.8450,-4.6078,2.8039,5.4153,0.4971,-2.1239,-1,3.6662
2366,9.0062,4.0647,3.6589,7.1548,5.4690,1.0835,0.7329,1,G,6.8066,-3.6342,-4.3498,-3.7670,5.6681,-0.6234,-2.2668,-1,15.4241
85046,13.7985,-6.6956,-6.5969,-10.1013,9.3995,-0.9332,-2.3636,-1,G,9.7331,5.5867,5.9994,5.2458,8.1978,0.6027,0.8210,1,22.9907

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100000 entries, 85820 to 85046
Data columns (total 18 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   E1      100000 non-null  float64
 1   px1     100000 non-null  float64
 2   py1     100000 non-null  float64
 3   pz1     100000 non-null  float64
 4   pt1     100000 non-null  float64
 5   eta1    100000 non-null  float64
 6   phi1    100000 non-null  float64
 7   Q1      100000 non-null  int64
 8   type2   100000 non-null  object
 9   E2      100000 non-null  float64
 10  px2     100000 non-null  float64
 11  py2     100000 non-null  float64
 12  pz2     100000 non-null  float64
 13  pt2     100000 non-null  float64
 14  eta2    100000 non-null  float64
 15  phi2    100000 non-null  float64
 16  Q2      100000 non-null  int64
 17  M       100000 non-null  float64
dtypes: float64(15), int64(2), object(1)
memory usage: 14.5+ MB

In [5]:
data.isnull()

,E1,px1,py1,pz1,pt1,eta1,phi1,Q1,type2,E2,px2,py2,pz2,pt2,eta2,phi2,Q2,M
85820,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
38382,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
15831,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
82644,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
7802,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48193,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
64597,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
38959,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2366,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
85046,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [6]:
data.isnull().sum()

E1       0
px1      0
py1      0
pz1      0
pt1      0
eta1     0
phi1     0
Q1       0
type2    0
E2       0
px2      0
py2      0
pz2      0
pt2      0
eta2     0
phi2     0
Q2       0
M        0
dtype: int64

In [ ]:
plt.figure(figsize=(16, 6))
sns.heatmap(data.isnull(),cmap='viridis')

In [ ]:
data.dropna(inplace=True)

In [ ]:
data.isnull().sum()

In [ ]:
data.head()

In [ ]:
type2=pd.get_dummies(data['type2'],drop_first=True,dtype=float)
type2

In [ ]:
data=pd.concat([data,type2],axis=1)
data.head()

In [ ]:
data.drop(['type2'],axis=1,inplace=True)
data.head()

In [ ]:
data.info()

In [ ]:
# creation of correlation matrix
corrM = data.corr()
plt.figure(figsize=(16, 6))
dataplot = sns.heatmap(corrM, cmap="YlGnBu", annot=True)

In [ ]:
corrM[corrM['E2']>0.1][['E2']]

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x=data.drop(['E2'],axis=1)
x=data[['E1','pt1','pt2','M']]

x.head()

In [ ]:
y=data['E2']
y

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.005, random_state=42)

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
model=LinearRegression()

In [ ]:
model.fit(X_train,y_train)

In [ ]:
pred=model.predict(X_test)
pred

In [ ]:
y_test

In [ ]:
X_test

In [ ]:
model.score(X_test, y_test)

In [ ]:
pred

In [ ]:
y_test

In [ ]:
indexes = X_test.index.values
len(indexes)

In [ ]:
plt.figure(figsize=(32, 16))
plt.plot(range(0,len(indexes)),y_test, color="orange", linewidth=3)
plt.plot(range(0,len(indexes)),pred, color="blue", linewidth=1)
plt.show()